https://travis-ci.org/tomitribe/beryllium.svg?branch=master[image:https://travis-ci.org/tomitribe/beryllium.svg?branch=master[Build
Status]]
https://coveralls.io/github/tomitribe/beryllium?branch=master[image:https://coveralls.io/repos/tomitribe/beryllium/badge.svg?branch=master&service=github[Coverage
Status]]
https://www.versioneye.com/user/projects/5621a1b736d0ab0021000abf[image:https://www.versioneye.com/user/projects/5621a1b736d0ab0021000abf/badge.svg[Dependency
Status]]
https://maven-badges.herokuapp.com/maven-central/org.tomitribe/beryllium[image:https://maven-badges.herokuapp.com/maven-central/org.tomitribe/beryllium/badge.svg[Maven
Central]]

[[beryllium]]
= Beryllium

Functional testing for REST API, Database setup, external service mocks
and redis setup/assertions

This is based on https://github.com/cucumber/cucumber-jvm[cucumber-jvm]
project.

You need to specify your features in the gherkin language and run it
with https://github.com/cucumber/cucumber-java-skeleton[cucumber-java]
or https://github.com/cukespace/cukespace[cukespace] + http://arquillian.org/[arquillian]

* link:#beryllium[Beryllium]
* link:#dependency[Dependency]
* link:#call-restful-apis-and-assert-responses[Call Restful APIs and
assert Responses]
* link:#mock-externals-api-calls[Mock externals API calls]
* link:#redis-assertions-and-setup[Redis assertions and setup]
* link:#run-the-cucumber-tests[Run the cucumber tests]

[[dependency]]
== Dependency

*Add as dependency in your pom.xml:*

[source,xml]
----
<dependency>
    <groupId>org.tomitribe</groupId>
    <artifactId>beryllium</artifactId>
    <version>${beryllium.version}</version>
    <scope>test</scope>
</dependency>
----

[[database-setup]]
== Database Setup

*Steps for Database Setup and verification of Endpoints Results*

Put your database connection properties in `src/test/resources/test-db.properties`

[source,properties,indent=0]
----
include::src/test/resources/test-db.properties[lines=20..23]
----

Write your feature in gherkin language in `src/test/resources/features/example.feature`

_it should be used in `Given` steps to prepare the database_

[source,gherkin,indent=0]
----
include::src/test/resources/features/database-setup.feature[]
----

[[call-restful-apis-and-assert-responses]]
== Call Restful APIs and assert Responses

*Steps to verify Restful API reponses*

[source,gherkin,indent=0]
----
include::src/test/resources/features/restful-endpoints.feature[]
----

[[mock-externals-api-calls]]
== Mock externals API calls

[source,gherkin,indent=0]
----
include::src/test/resources/features/mock-service.feature[]
----

And then put the payloads (convention over configuration) in `src/test/resources/restito`: i.e. `get.user.71e7cb11.json`

[source,json]
----
{
    "sample": 21
}
----

[[redis-assertions-and-setup]]
== Redis assertions and setup

[source,gherkin,indent=0]
----
include::src/test/resources/features/redis.feature[]
----

[[database-assertions]]
== Database assertions

Write your feature in gherkin language in
`src/test/resources/features/example.feature`

_it should be used in `Then` steps to check the database_

[source,gherkin,indent=0]
----
include::src/test/resources/features/database-assertions.feature[]
----

[[run-the-cucumber-tests]]
== Run the cucumber tests

*Write a cucumber integration-test in `src/test/java`:*

[source,java]
----
import org.junit.runner.RunWith;

import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;

@RunWith(Cucumber.class)

@CucumberOptions(
        snippets = SnippetType.CAMELCASE,
        strict = true,
        glue = {"classpath:"},
        features = {"classpath:features"},
        format = {"pretty"}
)
public class MyCucumberStory {
}
----
